name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  lint-test-build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Verify Go installation
        run: go version

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2

      - name: Clean Go modules
        run: |
          go clean -modcache
          go mod tidy
          go mod verify

      - name: Run tests
        run: go test -v ./...

      - name: Build binary
        run: go build -o webflix

  docker-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: lint-test-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webflix:${{ github.run_id }}

  update-helm-tag:
    name: Update Helm Chart Tag
    runs-on: ubuntu-latest
    needs: docker-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Helm chart image tag
        run: |
          sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" helm/webflix-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI Bot"
          git add helm/webflix-chart/values.yaml
          git commit -m "Update Helm tag to ${{ github.run_id }}"
          git push
